# Generated by Django 3.1.6 on 2021-02-12 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='admin',
            field=models.IntegerField(default='1'),
        ),
    ]
