# Generated by Django 3.1.6 on 2021-02-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_hospital_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='priority',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_attributes',
            name='ckd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_attributes',
            name='copd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_attributes',
            name='immunocompromised',
            field=models.BooleanField(default=False),
        ),
    ]
