# Generated by Django 3.1.6 on 2021-02-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210215_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='total_Vaccine',
        ),
        migrations.AddField(
            model_name='hospital',
            name='que',
            field=models.IntegerField(default=0),
        ),
    ]
